### ISSUE TITLE
use multiple templates at the same time

### ISSUE THREAD

**Issue by mattiak14** [vojtasvoboda/oc-userexportpdf-plugin#5]
Hello
with this plugin I can create another template ... but then I could have a button for each template so you can download 2 different versions on the user list?
or can I choose only one version to use?
thanks

**Comment by vojtasvoboda** [comment]
Hello @mattiak14, yes you can create more templates, but you can use only one template at a time. You can find this template at `/plugins/vojtasvoboda/userexportpdf/config/config.php`.
