### ISSUE TITLE
Frontend use

### ISSUE THREAD

**Issue by mattiak14** [vojtasvoboda/oc-userexportpdf-plugin#6]
Hello
is it possible to implement this plugin on a cms page of the frontend? how?
thank you so much

**Comment by vojtasvoboda** [comment]
Hello,

yes sure, just call method [PdfExportBehavior.php->pdf()](https://github.com/vojtasvoboda/oc-userexportpdf-plugin/blob/master/behaviors/PdfExportBehavior.php#L14) with user's ID as first parameter. This method automatically starts the download of PDF.

**Comment by mattiak14** [comment]
I'm sorry but I'm at my first project with octobercms ..
could you be more precise?
from the backend I saw that just call a url like "../backend/rainlab/user/users/pdf/149"
..
for the frontend? can I put some code directly on the cms page? or what?

thanks

**Comment by vojtasvoboda** [comment]
In template:

```
<p>
    <button data-request="onDownload">Download</button>
</p>
```

In code section:

```
use VojtaSvoboda\UserExportPdf\Behaviors\PdfExportBehavior;

function onDownload() {
    $downloader = new PdfExportBehavior($this);
    $userId = 1;

    return $downloader->pdf($userId);
}
```
